language: node_js
node_js:
  - "stable"
script:
  - npm test
  - npm run coverage
  - npm run coverage:coveralls
after_script:
  - cat ./build/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js